from .oracle_init import get_db_connection

def create_oracle_tables():
    """
    Oracle DB에 필요한 테이블을 생성합니다.
    테이블명: DEPOSIT
    id: 아이디
    account_holder: 예금주
    balance: 잔액
    테이블명: LOAN
    id: 아이디
    borrower: 대출자
    money: 대출금
    """

    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        # deposit 테이블 생성
        cursor.execute("""
            SELECT table_name
            FROM user_tables
            WHERE table_name = 'DEPOSIT'
        """)

        result = cursor.fetchone()
        if result:
            print("🎉 oracle_schema >> 'deposit' 테이블이 이미 존재합니다.")
        else:   
            cursor.execute("""
                CREATE TABLE deposit (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    account_holder VARCHAR2(100) NOT NULL,
                    balance NUMBER DEFAULT 0 NOT NULL 
                )
            """)
            
            print("🎉 oracle_schema >> 'deposit' 테이블 생성 성공.")

        # loan 테이블 생성
        cursor.execute("""
            SELECT table_name
            FROM user_tables
            WHERE table_name = 'LOAN'
        """)

        result = cursor.fetchone()
        if result:
            print("🎉 oracle_schema >> 'loan' 테이블이 이미 존재합니다.")
        else:
            cursor.execute("""
                CREATE TABLE loan (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    borrower VARCHAR2(100) NOT NULL,
                    money NUMBER DEFAULT 0 NOT NULL 
                )
            """)
            
            print("🎉 oracle_schema >> 'loan' 테이블 생성 성공.")
            
    except Exception as e:
        print(f"❌ oracle_schema >> 테이블 생성 에러: {e}")

    finally:
        cursor.close()
        conn.close()

def insert_deposit(account_holder: str, balance: int):
    """
    Oracle DB에 예시 데이터를 삽입합니다.
    DEPOSIT 테이블에 예금주가 중복되지 않는다면 데이터를 삽입합니다.
    """

    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        cursor.execute("""
            SELECT id 
            FROM deposit 
            WHERE account_holder = :account_holder
            """, account_holder=account_holder
        )

        result = cursor.fetchone()
        if result:
            print(f"🎉 oracle_schema >> 해당 예금주의 데이터 이미 존재: {result[0]}")
            return
        
        cursor.execute("""
            INSERT INTO deposit (account_holder, balance)
            VALUES (:account_holder, :balance)
            """, account_holder=account_holder, balance=balance
        )

        conn.commit()
        print(f"🎉 oracle_schema >> 데이터 삽입 성공: {account_holder}, {balance}")

    except Exception as e:
        print(f"❌ oracle_schema >> 데이터 조회 에러: {e}")

    finally:
        cursor.close()
        conn.close()

def insert_loan(borrower: str, money: int):
    """
    Oracle DB에 예시 데이터를 삽입합니다.
    LOAN 테이블에 대출자가 중복되지 않는다면 데이터를 삽입합니다.
    """

    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        cursor.execute("""
            SELECT id 
            FROM loan 
            WHERE borrower = :borrower
            """, borrower=borrower
        )

        result = cursor.fetchone()
        if result:
            print(f"🎉 oracle_schema >> 해당 대출자의 데이터 이미 존재: {result[0]}")
            return
        
        cursor.execute("""
            INSERT INTO loan (borrower, money)
            VALUES (:borrower, :money)
            """, borrower=borrower, money=money
        )

        conn.commit()
        print(f"🎉 oracle_schema >> 데이터 삽입 성공: {borrower}, {money}")

    except Exception as e:
        print(f"❌ oracle_schema >> 데이터 조회 에러: {e}")

    finally:
        cursor.close()
        conn.close()